# Generated by Django 2.1.11 on 2019-11-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_auto_20190809_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product4',
            new_name='ProductCU',
        ),
        migrations.RenameModel(
            old_name='Product3',
            new_name='ProductEmart24',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductGS25',
        ),
        migrations.RenameModel(
            old_name='Product2',
            new_name='ProductMiniStop',
        ),
        migrations.RenameModel(
            old_name='Product5',
            new_name='ProductSevenvEleven',
        ),
    ]
