# Generated by Django 2.1.11 on 2019-11-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0004_auto_20191115_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsevenveleven',
            name='prodName',
            field=models.CharField(max_length=255),
        ),
    ]
