# Generated by Django 2.1.11 on 2019-11-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_auto_20191126_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcu',
            name='prodName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productemart24',
            name='prodName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productgs25',
            name='prodName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productministop',
            name='prodName',
            field=models.CharField(max_length=255),
        ),
    ]
